### ISSUE TITLE
open res.pak will not work

### ISSUE THREAD

**Issue by jonatanYanovsky** [ReBuilders101/CellPacker#5]
I downloaded the CellPacker.jar and placed it in my dead cells directory. 
After doing File > Open "res.pak" > open-file window closes, nothing happens in cellpacker window, no files are opened.

Am I doing something wrong?

**Comment by raeneau** [comment]
Hello! I know this is ages later but I just ran into the same problem. Looked into the code a bit and it looks like Java is running out of memory, try going in the command line inside the dead cells folder and typing this:
`java -Xmx2048m -jar CellPacker.jar`
It'll run the file with more memory. I've tried lower mem amounts but 2048 seems to do the trick.

**Comment by jonatanYanovsky** [comment]
Hi! Thank you for your reply, I just reinstalled Dead Cells to try it out
running cmd prompt, I had to do the following as well to get it to even open:
`set _JAVA_OPTIONS="-Xmx512M"`
and I can't open res.pak due to java.lang.OutOfMemoryError heap space crashes

edit:
for some reason, I can run CellPacker by double clicking it
was able to open res.pak
